### ISSUE TITLE
Executor seems not to respect `commit_size` and `commit_timeout` 

### ISSUE THREAD

**Issue by snork-alt** [getdozer/dozer#1029]
With the following executor configuration

## Scenario 1 
```
impl Default for ExecutorOptions {
    fn default() -> Self {
        Self {
            commit_sz: 10_000,
            channel_buffer_sz: 50_000,
            commit_time_threshold: Duration::from_millis(50),
            max_map_size: 1024 * 1024 * 1024 * 1024,
        }
    }
}
```
we start processing around 30k rec/sec. This drops very quickly to 10-15k rec/sec.

## Scenario 2
Changing these numbers to: 

```
impl Default for ExecutorOptions {
    fn default() -> Self {
        Self {
            commit_sz: 1_000_000,
            channel_buffer_sz: 1_000_000,
            commit_time_threshold: Duration::from_millis(100_000),
            max_map_size: 1024 * 1024 * 1024 * 1024,
        }
    }
}
```
we have similar behavior. we start processing about 90k rec/sec which quickly drops to 10-15k rec/ sec

## Scenario 3
However if we disable commit in the cache:

```
  fn commit(&mut self, _epoch: &Epoch, _tx: &SharedTransaction) -> Result<(), ExecutionError> {
        let endpoint_name = self.api_endpoint.name.clone();
        // Update Counter on commit
        self.pb.set_position(self.counter as u64);
        // self.cache.commit().map_err(|e| {
        //     ExecutionError::SinkError(SinkError::CacheCommitTransactionFailed(
        //         endpoint_name,
        //         Box::new(e),
        //     ))
        // })?;
        Ok(())
```

we keep a sustained rate of 55-90k rec/ sec

Scenario 2 and Scenario 3 should produce the same results as the executor portions for scenario 2 are incredibly high and should cause teh pipeline and cache to never commit before 1m messages or 100s

**Comment by chubei** [comment]
Which sample you're using?

**Comment by snork-alt** [comment]
NY taxi. I can give you the exact config file

**Comment by chubei** [comment]
BTW if you use the code on `main`, `ExecutorOptions::default` is not used after https://github.com/getdozer/dozer/pull/946

**Comment by chubei** [comment]
> NY taxi. I can give you the exact config file

Let me check

**Comment by chubei** [comment]
Reporting peak performance (reached seconds after the app is started) on my machine:

With code in https://github.com/getdozer/dozer/commit/dbc5af9b459f524099f1ddb7f659b90837cda5a6, data and config in https://github.com/getdozer/dozer-samples-internal/commit/6564262295702fdc5cef225cd17db635d3d948a0, trips_cache: 23k/s

With code in https://github.com/chubei/dozer/commit/cf2aa97bc449d2256456ea879e3fc6f9b48a4b22, data and config in https://github.com/getdozer/dozer-samples-internal/commit/6564262295702fdc5cef225cd17db635d3d948a0, trips_cache: 23k/s

With code in https://github.com/chubei/dozer/commit/d62090da3f4156735009eff2d13b01b33774beea, data and config in https://github.com/getdozer/dozer-samples-internal/commit/6564262295702fdc5cef225cd17db635d3d948a0, trips_cache: 27k/s

Changing `ExecutorOptions::default` won't change performance because it's not used. I think this bug doesn't exist.
