### ISSUE TITLE
Handle endpoint REST path collision properly

### ISSUE THREAD

**Issue by chubei** [getdozer/dozer#1547]
Currently we don't do any sanity check on `endpoint.path`. If one endpoint uses a path that's a prefix of a later endpoint's path, the later one is silently not served, because path matching will always match the former endpoint first.

**Comment by crajcan** [comment]
I was looking into working on this so I wrote a test to make sure we're on the same page: 

https://github.com/getdozer/dozer/pull/1693

**Comment by chubei** [comment]
Hi @crajcan! Thank you for looking into this!

I checked your test and that's exactly the problem we're trying to fix. Do you mind sharing your thoughts on how you plan to tackle this?

**Comment by crajcan** [comment]
> Hi @crajcan! Thank you for looking into this!
> 
> I checked your test and that's exactly the problem we're trying to fix. Do you mind sharing your thoughts on how you plan to tackle this?

Awesome!

The first thought I had was for a somewhat naive solution. The `cache_endpoints` would be reverse sorted by the length of the `path` before the respective `Scope` would be attached to the `app`. This would allow a path like `/users/posts` to be matched before `/users`.

The second implementation I thought of would be to build a tree out of the `cache_endpoint` paths. A path like `/users/posts` would become a child node of a node for `/users`. This way we could traverse the tree to create a `Scope` for the lowest nodes first, attach the default routes (`/count`, `/query`, `phase`, etc...) to that `Scope`, then attach the `Scope` to its parent `Scope` once the parent `Scope` is built. Once all of the root level `Scope`s are built, they would be added to the `app`.

The second solution might play better with future adjustments the routing logic, and if actix provides a way to generate an index of the available routes, it might provide a prettier output. But I'm not sure if it's necessary otherwise. 

Let me know if you had any other thoughts.

**Comment by chubei** [comment]
Either solution sounds good to me!
